### ISSUE TITLE
decouple devices from humans

### ISSUE THREAD

**Issue by jeborsel** [oSoc20/bit-of-trust#1]
1 device -> multiple humans
1 human -> multiple devices

> Users are responsible for the safe-guarding of their private key, both from attackers and from being lost, and for distributing it across their devices

don't think this is a necessity .
Users are responsible for safe-guarding their devices (if they feel that need, how humans authenticate towards devices is out of scope of this protocol). 
Devices are fixed endpoints. Humans are not, relationships of humans vs devices & humans vs humans are.

**Comment by timplication** [comment]
We have not yet decided on how we will implement the relation between devices and members of the trust relationship. To signal this fact, we have renamed 'device identifiers' to 'trust shards' as this indicates more clearly what we are actually trying to accomplish with this (c.f. my answer on issue #2). Think of these 'trust shards' as interchangeable pieces of the trust relationship that signal that you are a part of it.

Our future work would be to find a way to exchange these shards between devices and other users, without losing the authenticity of a given trust shard. The reason we are currently using public key cryptography is for authenticity of a trust shard, that is, we do not want people to fake a shard or claim that they own a shard when they do not.

**Comment by timplication** [comment]
> Users are responsible for the safe-guarding of their private key, both from attackers and from being lost, and for distributing it across their devices

Addendum: just because we are using asymmetric cryptography, it does not necessarily mean that users have to use the terminal or remember long strings of text. It is perfectly possible to hide this under the hood in a user friendly application.
